### PR TITLE
Bugfix: allow annotations on parent assignments with released peer reviews

### LINKED ISSUE #7184: Unable to annotate source assignments after peer review release
After releasing peer reviews for a submission, the source assignment's submission cannot be annotated.

Steps to reproduce:

1. As a student, mark a peer review for another student as complete
2. As the instructor, release the peer review that was just completed
3. Go to the grading view for the reviewee's submission on the source assignment
4. Attempt to add an annotation

This will result in an HTTP `422` error (but no user-facing error message).

If the peer review is subsequently unreleased, annotations behave as expected.

### PR DESCRIPTION
**Pull request by pretendWhale**
## Proposed Changes
*(Describe your changes here. Also describe the motivation for your changes: what problem do they solve, or how do they improve the application or codebase? If this pull request fixes an open issue, [use a keyword to link this pull request to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).)*
Currently, if a submission has a released peer review, the annotation validations prevent adding new annotations on the result in the parent assignment. This is a bug, which this PR fixes. Resolves #7184 
...

<details>
<summary>Screenshots of your changes (if applicable)</summary>

</details>

<details>
<summary>Associated <a href="https://github.com/MarkUsProject/Wiki">documentation repository</a> pull request (if applicable)</summary>

</details>

## Type of Change
*(Write an `X` or a brief description next to the type or types that best describe your changes.)*

| Type                                                                                    | Applies? |
|-----------------------------------------------------------------------------------------|----------|
| 🚨 *Breaking change* (fix or feature that would cause existing functionality to change) |          |
| ✨ *New feature* (non-breaking change that adds functionality)                          |          |
| 🐛 *Bug fix* (non-breaking change that fixes an issue)                                  |      x   |
| 🎨 *User interface change* (change to user interface; provide screenshots)              |          |
| ♻️ *Refactoring* (internal change to codebase, without changing functionality)          |          |
| 🚦 *Test update* (change that *only* adds or modifies tests)                            |          |
| 📦 *Dependency update* (change that updates a dependency)                               |          |
| 🔧 *Internal* (change that *only* affects developers or continuous integration)         |          |

## Checklist
*(Complete each of the following items for your pull request. Indicate that you have completed an item by changing the `[ ]` into a `[x]` in the raw text, or by clicking on the checkbox in the rendered description on GitHub.)*

Before opening your pull request:

- [x] I have performed a self-review of my changes.
  - Check that all changed files included in this pull request are intentional changes.
  - Check that all changes are relevant to the purpose of this pull request, as described above.
- [x] I have added tests for my changes, if applicable.
  - This is **required** for all bug fixes and new features.
- [ ] I have updated the project documentation, if applicable.
  - This is **required** for new features.
- [ ] If this is my first contribution, I have added myself to the list of contributors.

After opening your pull request:

- [x] I have updated the project Changelog (this is required for all changes).
- [x] I have verified that the pre-commit.ci checks have passed.
- [x] I have verified that the CI tests have passed.
- [ ] I have reviewed the test coverage changes reported by Coveralls.
- [ ] I have [requested a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from a project maintainer.

## Questions and Comments
*(Include any questions or comments you have regarding your changes.)*

### CODE REVIEW

**Review by donny-wong — APPROVED** [review]

File: app/models/annotation.rb [hunk 1]
```diff
@@ -72,6 +72,8 @@ def check_if_released
 
     return if result.is_a_review? && !result.released_to_students
 
+    return if result.submission.non_pr_results.where('results.released_to_students': true).empty?
```
Comment (david-yz-liu) [inline app/models/annotation.rb:75]: I'm not convinced another check is necessary. Can't we modify line 65 to use `non_pr_results`?

Comment (pretendWhale) [reply app/models/annotation.rb]: @david-yz-liu Thanks! I think you are correct, and in fact this logic is better.

**Review by david-yz-liu — APPROVED** [review]
