### PR TITLE
Issue 6450

### LINKED ISSUE #6450: Trailing spaces on MarkUs file preview
**Description**
When using the MarkUs Web file viewer, there are two trailing spaces after every line. This is mildly inconvenient when copy pasting text or code directly from the MarkUs website into a code editor.

**Screenshot of MarkUs file preview:**
image

**Reproduction Steps**
1. Go to a MarkUs assignment repository
2. Click on a file to open the preview
3. Highlight the text, and it will reveal the additional spaces

### PR DESCRIPTION
**Pull request by khushiagl**
## Motivation and Context

When viewing a file on MarkUs, there were trailing spaces after every line which made it inconvenient to copy-paste code. 
Closes #6450 

## Your Changes

**Description**:
Edited Code Syntax Highlighter to remove the trailing spaces. 

**Type of change** (select all that apply):

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

Tested through UI

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have verified that the pre-commit.ci checks have passed. 
- [x] I have verified that the CI tests have passed. 
- [x] I have reviewed the test coverage changes reported on Coveralls. 
- [x] I have updated the Changelog.md file.

### CODE REVIEW

File: vendor/assets/javascripts/syntaxhighlighter_lib/shCore.js [hunk 1]
```diff
@@ -385,7 +385,8 @@ dp.sh.Highlighter.prototype.SwitchToList = function() {
     var li = this.CreateElement('LI');
     var span = this.CreateElement('SPAN');
 
-    span.innerHTML = lines[i] + '&nbsp;';
+    if(lines[i] === "") { span.innerHTML = lines[i] + '&nbsp;'; }
```
Comment (david-yz-liu) [inline vendor/assets/javascripts/syntaxhighlighter_lib/shCore.js:388]: Put the body of if/else branches on separate lines after the if/else. Always use `{ }` to delimit bodies (i.e., don't do single-line branches).

Also, in the `if` case the `lines[i]` is empty, so doesn't need to be included when setting `span.innerHTML`.

**Review by david-yz-liu — APPROVED** [review]
