### PR TITLE
Fixed Grace Token Deductions to Use Display Name

### LINKED ISSUE #5610: Bug Report: Display name not used for grace token deductions
**Related Feature:** #4876 

**Reason for change:** People's official first name + last name are accidentally being shown to their group members.

**Current Behaviour:** 

GIVEN a user has a display name that is different from their first name and last name
AND they have a group for an assignment
AND the group submits the assignment after the due date, using some grace tokens
WHEN the assignment results are back
THEN their official first + last name are shown next to grace token deductions

**Expected Behaviour:**

GIVEN \<see above \>
WHEN \<see above \>
THEN _their display name_ is shown next to grace token deductions

----

**Where's the fix needed?:**
- In the summary panel of an assignment result
- See [app/assets/javascripts/Components/Result/summary_panel.jsx#L258](https://github.com/MarkUsProject/Markus/blob/master/app/assets/javascripts/Components/Result/summary_panel.jsx#L258)

### PR DESCRIPTION
**Pull request by anoverga17**
## Motivation and Context

This pull request fixes an issue whereby the results page which displays grace token deductions would show a user's first and last name in parentheses as opposed to their display name. 
In addition, the grace token deductions display for students was changed so that students can no longer see the grace token deductions for other group members (they can only see their own).

Resolves #5610

## Your Changes

**Description**:
- Changed grace token deductions summary display to show a student's display name rather than their first and last name. 
- When logged in as a student, changed grace token deductions summary display to show only that student's deductions.
- Added tests for changes as well as basic tests for other data provided from  the `results_contoller`'s `show` method.

**Type of change** (select all that apply):

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactoring (internal change to codebase, without changing functionality)

## Testing

Manual testing was done to ensure the appropriate display name was shown. In addition, this testing was done whilst logged in as an admin, grader, and student roles to ensure only the relevant grace token deductions were being shown for a specific user (i.e. students could only see their own grace token deductions whilst admins and graders can see every group member's deductions). 
This was further supplemented by adding rspec tests which checked that the appropriate data was being sent given the user who is currently logged in. 

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have fixed any Hound bot comments. 
- [x] I have verified that the CI tests have passed. 
- [x] I have reviewed the test coverage changes reported on Coveralls.

### CODE REVIEW

File: app/assets/javascripts/Components/Result/summary_panel.jsx [hunk 1]
```diff
@@ -253,10 +253,8 @@ export class SummaryPanel extends React.Component {
     } else {
       let rows = this.props.graceTokenDeductions.flatMap(d => {
         return [
-          <tr key={d["users.user_name"]}>
-            <th colSpan={2}>
-              {`${d["users.user_name"]} - (${d["users.first_name"]} ${d["users.last_name"]})`}
-            </th>
+          <tr key={d["users.user_name"]} align="left">
```
Comment (mishaschwartz) [inline app/assets/javascripts/Components/Result/summary_panel.jsx:256]: Please don't add formatting as an attribute, this should be added as part of the css. In this case especially, the align attribute is not supported by html5 and should not be used.

For this PR, please remove it and we can discuss whether we should adjust the alignment in a different PR later on.

File: app/controllers/results_controller.rb [hunk 2]
```diff
@@ -203,13 +203,19 @@ def show
           data[:grace_token_deductions] = []
         elsif current_user.ta? && assignment.anonymize_groups
           data[:grace_token_deductions] = []
-
+        elsif current_user.student?
```
Comment (mishaschwartz) [inline app/controllers/results_controller.rb:206]: This is great! Please also add a few tests for this as well.

**Review by mishaschwartz — CHANGES_REQUESTED** [review]

File: spec/controllers/results_controller_spec.rb [hunk 3]
```diff
@@ -479,6 +479,93 @@ def self.test_unauthorized(route_name)
     end
   end
 
+  shared_examples 'showing json data' do |is_student|
+    let(:student2) do
+      partner = create(:student, grace_credits: 2)
+      StudentMembership.create(user: partner,
```
Comment (mishaschwartz) [inline spec/controllers/results_controller_spec.rb:485]: This is fine for now but in the future, please use the factories when creating objects for tests:

```ruby
create :accepted_student_membership, user: partner, grouping: grouping
```

**Review by mishaschwartz — APPROVED** [review]

**Review by david-yz-liu — APPROVED** [review]
Thanks, @anoverga17!
