### PR TITLE
Markdown Support in Annotation and Other Areas

### LINKED ISSUE #2305: Use markdown as language for annotations
Would be nice if markdown can be used as the language for writing annotations.
For example, the library [RedCarpet](https://github.com/vmg/redcarpet) can be used for rendering markdown to html (I assume this is a rails app, correct me if I'm wrong).

### PR DESCRIPTION
**Pull request by finnergizer**
Closes #2305. Switched simple_format everywhere to use new `markdown(text)` view helper. Started with annotations, but then made a global switch (i.e. remark requests, overall comments).

### CODE REVIEW

File: app/views/annotations/update_annotation.js.erb [hunk 1]
```diff
@@ -9,6 +9,6 @@ document.getElementById('annotation_summary_list').innerHTML =
                                   locals: { annotation_category: @annotation_text.annotation_category }) %>';
 <% end %>
 
-update_annotation_text('<%= @annotation_text.id %>', '<%= escape_javascript(simple_format(@annotation_text.content)) %>');
+update_annotation_text('<%= @annotation_text.id %>', marked('<%= escape_javascript(simple_format(@annotation_text.content)) %>'));
```
Comment (david-yz-liu) [inline app/views/annotations/update_annotation.js.erb]: @finnergizer This is the only one that catches my eye. There's an inner call to `simple_format`, why not use `markdown` here?

Comment (finnergizer) [inline app/views/annotations/update_annotation.js.erb]: @david-yz-liu since this JS is rendered server-side, I used markdown helper instead and removed marked library use in this case. Good catch! Thanks!
