### PR TITLE
Fix renaming a group removes any associated submissions

### LINKED ISSUE #7215: Renaming a group removes any associated submissions
The following scenario will remove associated submissions when renaming the group for an assignment: 

**Pre-requisites:** An existing assignment where a group was created and renamed. 
(An existing example: the aaaautotest group for the prep02 assignment -- their repo is group_004) 

**Steps to reproduce:** 

1. In another assignment, create a group (this was group_3390) 
2. Add a submission to that group, collect, and run tests 
3. Rename the group (i.e. in this case, renamed group_3390 to aaaautotest) 
4. The renamed group's repository will now point to the one from the other assignment (i.e. the repo has changed from group_3390 to group_004). A few results of this: 

    - The submission will never be able to find the associated file 
    - But the automated test results will still be there 

Note: If the group was renamed to a non existent group, it won't switch repositories.

### PR DESCRIPTION
**Pull request by ch-iv**
## Proposed Changes
Fixes #7215, a bug where renaming a group to an existing group in a different assignment resulted in incorrect repository mapping.

## Type of Change
*(Write an `X` or a brief description next to the type or types that best describe your changes.)*

| Type                                                                                    | Applies? |
|-----------------------------------------------------------------------------------------|----------|
| 🚨 *Breaking change* (fix or feature that would cause existing functionality to change) |          |
| ✨ *New feature* (non-breaking change that adds functionality)                          |          |
| 🐛 *Bug fix* (non-breaking change that fixes an issue)                                  |     x     |
| 🎨 *User interface change* (change to user interface; provide screenshots)              |          |
| ♻️ *Refactoring* (internal change to codebase, without changing functionality)          |          |
| 🚦 *Test update* (change that *only* adds or modifies tests)                            |          |
| 📦 *Dependency update* (change that updates a dependency)                               |          |
| 🔧 *Internal* (change that *only* affects developers or continuous integration)         |          |

## Checklist
*(Complete each of the following items for your pull request. Indicate that you have completed an item by changing the `[ ]` into a `[x]` in the raw text, or by clicking on the checkbox in the rendered description on GitHub.)*

Before opening your pull request:

- [x] I have performed a self-review of my changes.
  - Check that all changed files included in this pull request are intentional changes.
  - Check that all changes are relevant to the purpose of this pull request, as described above.
- [x] I have added tests for my changes, if applicable.
  - This is **required** for all bug fixes and new features.
- [ ] I have updated the project documentation, if applicable.
  - This is **required** for new features.
- [ ] If this is my first contribution, I have added myself to the list of contributors.

After opening your pull request:

- [x] I have updated the project Changelog (this is required for all changes).
- [x] I have verified that the pre-commit.ci checks have passed.
- [x] I have verified that the CI tests have passed.
- [x] I have reviewed the test coverage changes reported by Coveralls.
- [x] I have [requested a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from a project maintainer.

## Questions and Comments
*(Include any questions or comments you have regarding your changes.)*

### CODE REVIEW

File: app/controllers/groups_controller.rb [hunk 1]
```diff
@@ -73,7 +72,9 @@ def rename_group
       params[:assignment_id] = @assignment.id
 
       if Grouping.exists?(assessment_id: @assignment.id, group_id: groupexist_id)
-        flash_now(:error, I18n.t('groups.group_name_already_in_use'))
+        flash.now[:error] = I18n.t('groups.group_name_already_in_use')
```
Comment (david-yz-liu) [inline app/controllers/groups_controller.rb:75]: This change is not appropriate; `flash_now` is the preferred helper method. Same on line 77.

File: app/controllers/groups_controller.rb [hunk 2]
```diff
@@ -58,13 +58,12 @@ def rename_group
...
     # Checking if a group with this name already exists
-    if (@groups = current_course.groups.where(group_name: params[:new_groupname]).first)
+    if (@existing_group = current_course.groups.where(group_name: params[:new_groupname]).first)
       existing = true
-      groupexist_id = @groups.id
+      groupexist_id = @existing_group.id
     end
 
     if existing
-
```
Comment (david-yz-liu) [inline app/controllers/groups_controller.rb:67]: revert this change

File: app/controllers/groups_controller.rb [hunk 3]
```diff
@@ -73,7 +72,9 @@ def rename_group
       params[:assignment_id] = @assignment.id
 
       if Grouping.exists?(assessment_id: @assignment.id, group_id: groupexist_id)
-        flash_now(:error, I18n.t('groups.group_name_already_in_use'))
+        flash.now[:error] = I18n.t('groups.group_name_already_in_use')
+      elsif @existing_group.has_non_empty_submission?
```
Comment (david-yz-liu) [inline app/controllers/groups_controller.rb:76]: Overall, this check is not exactly what I'm looking for.

1. The check should centre on `@grouping`, not `@existing_group`. The original issue was that files that had originally been submitted to `@grouping` could no longer be accessed after the repository switched, and so the check I want you to make is for whether `@grouping` has any submitted files.
2. It's great research that you found the `Grouping#has_non_empty_submission?` method, but that's actually too narrow for our purposes. A `Submission` object is only created after an instructor "collects" submissions, typically after the assignment deadline. However, students submit files before this collection process, and the check I'd like you to make is for whether students have submitted -- i.e., _uploaded_ -- any files to `@grouping`.

File: config/locales/views/groups/en.yml [hunk 4]
```diff
@@ -27,6 +27,7 @@ en:
     empty: Empty Group
     grace_day_over_limit: You have assigned one or more students who has less grace credits than the amount already used by group %{group} for this assignment.
     group_name_already_in_use: This name is already in use for this assignment.
+    group_name_already_in_use_diff_assignment: This name is already in use for a different assignment.
```
Comment (david-yz-liu) [inline config/locales/views/groups/en.yml:30]: Following my above comment, this error message doesn't quite communicate the right idea. The problem it should convey is something like "You're trying to rename to an existing group, which isn't allowed because you've already submitted a file." Please work off of that to create a new version of this error message.

File: spec/controllers/groups_controller_spec.rb [hunk 5]
```diff
@@ -135,7 +136,67 @@
...
+          }
+        end.to change { group.reload.group_name }.from('group1').to('renamed')
+      end
+
+      context 'group renaming and repository association' do
+        # Regression test for https://github.com/MarkUsProject/Markus/issues/7215, where renaming a group in an
+        # assignment would incorrectly associate the group's repository with one from another assignment, resulting in
+        # lost submissions and incorrect repository mappings.
+        let(:assignment2) { create(:assignment, course: course) }
+        let(:grouping_with_submission) { create(:grouping_with_inviter_and_submission, assignment: assignment2) }
```
Comment (david-yz-liu) [inline spec/controllers/groups_controller_spec.rb:157]: Following my above comment, this is a good test case, but you should another test case for when files have been submitted but submissions have not been collected.

File: spec/controllers/groups_controller_spec.rb [hunk 6]
```diff
@@ -135,7 +136,67 @@
...
+        let(:grouping_without_submission) { create(:grouping, assignment: assignment2) }
+
+        before do
+          grouping_with_submission.save
```
Comment (david-yz-liu) [inline spec/controllers/groups_controller_spec.rb:161]: Instead of doing this, you can use `let!` instead of `let` to define these variables. This will define them eagerly rather than lazily, ensuring they're created for each test case.

File: app/models/grouping.rb [hunk 7]
```diff
@@ -754,6 +754,19 @@ def get_random_incomplete(current_role)
     results.where.not('groupings.id': self.id).order('RANDOM()').first&.grouping
   end
 
+  # Checks if a grouping uploaded any files
+  def has_submitted_files?
+    access_repo do |repo|
+      revision = repo.get_revision_by_timestamp(Time.current)
+
+      files = revision.tree_at_path('/', with_attrs: false).select do |_, obj|
```
Comment (david-yz-liu) [inline app/models/grouping.rb:762]: Use `assignment.repository_folder` instead of `'/'` (e.g., see `assignments_controller.rb` line 802). This will check for this grouping's folder for this specific assignment.

**Review by david-yz-liu — COMMENTED** [review]
@ch-iv great work! I just left one small comment.

**Review by david-yz-liu — APPROVED** [review]
