### PR TITLE
Fix: only retain most recent test results

### LINKED ISSUE #7070: Download most recent test results
**Context:** 
In the Summary Tab, there is a “Download Test Results” button that downloads a file that contains the test results. However, when the tests get updated and one of the tests are removed, it will still show up on the download test results. It is preferable to only show the most recent relevant test results. In other words, the only tests that should show up are the ones that show up in the test results tab of the most recently run test.

### PR DESCRIPTION
**Pull request by pranavrao145**
## Proposed Changes
Fixes #7070 by making the "Download Test Results" button on the Summary page look at the latest test run to determine for which test groups the results must be downloaded, and downloads them accordingly. So, if a user deletes a test group and runs the tests again, the next summary would not contain the deleted test groups. This is in contrast to the original behaviour, where the latest results of _every_ test group would _always_ be part of the JSON/CSV summary.

## Type of Change
*(Write an `X` or a brief description next to the type or types that best describe your changes.)*

| Type                                                                                    | Applies? |
|-----------------------------------------------------------------------------------------|----------|
| 🚨 *Breaking change* (fix or feature that would cause existing functionality to change) |          |
| ✨ *New feature* (non-breaking change that adds functionality)                          |          |
| 🐛 *Bug fix* (non-breaking change that fixes an issue)                                  |     X     |
| 🎨 *User interface change* (change to user interface; provide screenshots)              |          |
| ♻️ *Refactoring* (internal change to codebase, without changing functionality)          |          |
| 🚦 *Test update* (change that *only* adds or modifies tests)                            |          |
| 📦 *Dependency update* (change that updates a dependency)                               |          |
| 🔧 *Internal* (change that *only* affects developers or continuous integration)         |          |

## Checklist
*(Complete each of the following items for your pull request. Indicate that you have completed an item by changing the `[ ]` into a `[x]` in the raw text, or by clicking on the checkbox in the rendered description on GitHub.)*

Before opening your pull request:

- [x] I have performed a self-review of my changes.
  - Check that all changed files included in this pull request are intentional changes.
  - Check that all changes are relevant to the purpose of this pull request, as described above.
- [x] I have added tests for my changes, if applicable.
  - This is **required** for all bug fixes and new features.

After opening your pull request:

- [x] I have updated the project Changelog (this is required for all changes).
- [x] I have verified that the pre-commit.ci checks have passed.
- [x] I have verified that the CI tests have passed.
- [x] I have reviewed the test coverage changes reported by Coveralls.
- [x] I have [requested a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from a project maintainer.

### CODE REVIEW

File: app/models/assignment.rb [hunk 1]
```diff
@@ -634,27 +634,29 @@ def summary_json(user)
...
+    latest_test_runs = TestRun.joins("INNER JOIN (#{latest_test_run_by_grouping}) latest_test_run_by_grouping \
+                  ON latest_test_run_by_grouping.grouping_id = test_runs.grouping_id \
+                  AND latest_test_run_by_grouping.test_runs_created_at = test_runs.created_at")
+                              .select('id', 'submission_id', 'grouping_id')
+                              .to_sql
+
+    self.test_groups.joins(test_group_results: :test_results)
+        .joins("INNER JOIN (#{latest_test_runs}) latest_test_runs \
+              ON test_group_results.test_run_id = latest_test_runs.id")
+        .joins('INNER JOIN groupings ON latest_test_runs.grouping_id = groupings.id')
```
Comment (david-yz-liu) [inline app/models/assignment.rb:649]: It's a good idea to reduce the number of joins, but in order to take better advantage of ActiveRecord methods, you can move these joins into the definition of `latest_test_runs` (`TestRun.joins(grouping: group)`) and add the relevant fields to the `select`.

File: app/models/assignment.rb [hunk 2]
```diff
@@ -634,22 +634,26 @@ def summary_json(user)
...
+                       .joins("INNER JOIN (#{latest_test_run_by_grouping}) latest_test_run_by_grouping \
+            ON latest_test_run_by_grouping.grouping_id = test_runs.grouping_id \
+            AND latest_test_run_by_grouping.test_runs_created_at = test_runs.created_at")
+                       .select('id', 'test_runs.grouping_id', 'groups.group_name')
+                       .to_sql
+
+    self.test_groups.joins(test_group_results: :test_results)
+        .joins("INNER JOIN (#{latest_test_runs}) latest_test_runs \
+              ON test_group_results.test_run_id = latest_test_runs.id")
+        .joins('INNER JOIN groupings ON latest_test_runs.grouping_id = groupings.id')
```
Comment (david-yz-liu) [inline app/models/assignment.rb:653]: @pranavrao145 Oh wait, so actually now do we need a join on `groupings` at all? Seems like the only necessary information was to use the grouping to access the corresponding group name, but that's now been moved.

Comment (pranavrao145) [reply app/models/assignment.rb:653]: Good point! No need to join it again, I will get rid of this one.

**Review by david-yz-liu — APPROVED** [review]
