### PR TITLE
close #2042

### LINKED ISSUE #2042: Removing an image annotation does not remove the highlighted area on the image
Steps to reproduce:
1) Collect and grade a submission
2) Open a picture file (I've found this issue with jpg's)
3) Highlight an area and add an annotation using the annotation dropdowns (not sure what the correct name is)
4) Switch from the "Source Code" tab to the "Annotations" tab and remove the added annotation
5) Switch back to source code to see that the previously highlighted are is still highlighted but shows no annotation on mouse hover

### PR DESCRIPTION
**Pull request by wkwan**

### CODE REVIEW

File: app/assets/javascripts/SourceCodeGlower/ImageAnnotationGrid.js [hunk 1]
```diff
@@ -119,6 +119,11 @@ ImageAnnotationGrid.prototype.add_to_grid = function(extracted_coords) {
 ImageAnnotationGrid.prototype.remove_annotation = function(unused_param1, unused_param2, annotation_text_id) {
   if (this.getAnnotationTextManager().annotationTextExists(annotation_text_id)) {
     this.getAnnotationTextManager().removeAnnotationText(annotation_text_id);
+    var holder = document.getElementById('annotation_holder_' + annotation_text_id);
+    if (holder != null) 
+    {
```
Comment (david-yz-liu) [inline app/assets/javascripts/SourceCodeGlower/ImageAnnotationGrid.js]: In general, put the opening brace on the previous line.

**Comment by david-yz-liu** [comment]
Thanks, @wkwan!
